wip: fix metaclass conflict error
- After splitting the worker, workflow, and activity into their own
  modules, I started to see workflow task error:

    TypeError: metaclass conflict: the metaclass of a derived class
    must be a (non-strict) subclass of the metaclasses of all its bases

- Fix the above error by explicitly passing through "sentry_sdk" to
  the workflow sandbox in the worker options